- name: Deploy Spring Boot WAR Application
  hosts: web_servers
  become: no
  roles:
    - java
    - tomcat
    - spring-boot-app

  handlers:
    - name: restart tomcat
      become: yes
      ansible.builtin.systemd:
        name: tomcat
        state: restarted