- name: Deploy Spring Boot Application with MySQL
  hosts: web_servers
  become: no
  roles:
    - java
    - mysql
    - spring-boot-app

  handlers:
    - name: restart mysql
      become: yes
      ansible.builtin.systemd:
        name: mysqld
        state: restarted

    - name: Restart Spring Boot App
      become: yes
      ansible.builtin.systemd:
        name: spring-boot-app
        state: restarted
