- name: Deploy Spring Boot Application
  hosts: web_servers
  become: no
  roles:
    - java
    - mysql
    - spring-boot-app

  pre_tasks:
    - name: Install Ansible on the target node (for Amazon Linux 2023)
      become: yes
      ansible.builtin.dnf:
        name: ansible-core
        state: present
      when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"

  handlers:
    - name: Restart Spring Boot App
      become: yes
      ansible.builtin.systemd:
        name: spring-boot-app
        state: restarted
