- name: Create application directory
  ansible.builtin.file:
    path: "{{ remote_app_dir }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "0755"

- name: Copy Spring Boot JAR to remote server
  ansible.builtin.copy:
    src: "{{ app_jar_path }}"
    dest: "{{ remote_app_dir }}/{{ remote_app_jar_name }}"
  notify: Reload systemd and restart app

- name: Create systemd service file from template
  ansible.builtin.template:
    src: app.service.j2
    dest: /etc/systemd/system/springboot-app.service
  notify: Reload systemd and restart app
