name: 'Deploy Spring Boot App with Ansible'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy with Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List all files in the repository
        run: ls -R

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Ansible
        run: |
          python3 -m pip install --user ansible
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check current directory before running playbook
        run: |
          echo "現在のディレクトリ:"
          pwd
          echo "ファイル一覧:"
          ls -la

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/playbook.yml -i ansible/inventory.ini
