name: 'Deploy Spring Boot App with Ansible'

on:
  push:
    branches:
      - main
      - ansible
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy with Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Ansible
        run: |
          python3 -m pip install --user ansible
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run Ansible Playbook
        run: ansible-playbook RaiseTech-ansible/ansible/playbook.yml -i RaiseTech-ansible/ansible/inventory.ini
