- name: Install MySQL Community Server
  yum:
    name: mysql-community-server
    state: present
  when: ansible_distribution == "Amazon Linux" and ansible_distribution_major_version == "2023"

- name: Start and enable MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Secure MySQL installation
  shell: mysql_secure_installation
  args:
    removes:
      - /var/log/mysqld.log
    creates: /var/log/mysqld.log
  when: ansible_distribution == "Amazon Linux" and ansible_distribution_major_version == "2023"
  tags: secure
