- name: Update all packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Find available MySQL packages
  shell: dnf list available | grep -i mysql
  register: mysql_packages
  changed_when: false
  failed_when: false

- name: Debug available MySQL packages
  debug:
    var: mysql_packages.stdout_lines

- name: Download MySQL repo RPM
  get_url:
    url: https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
    dest: /tmp/mysql80-community-release-el9-1.noarch.rpm
    mode: "0644"

- name: Install MySQL repo
  dnf:
    name: /tmp/mysql80-community-release-el9-1.noarch.rpm
    state: present
  failed_when: false

- name: Enable MySQL repo
  shell: dnf config-manager --enable mysql80-community
  failed_when: false

- name: Install MySQL server from MySQL Community repo
  dnf:
    name: mysql-community-server
    state: present

- name: Start and enable MySQL service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host_all: yes
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
