- name: Update all packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Install MySQL server
  dnf:
    name: mysql-server
    state: present

- name: Start and enable MySQL service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host_all: yes
    login_unix_socket: /var/lib/mysql/mysql.sock
  no_log: true
