- name: Update all packages
  dnf:
    name: '*'
    state: latest
    update_cache: yes

- name: Install MariaDB server (MySQL compatible)
  dnf:
    name: mariadb-server
    state: present

- name: Start and enable MySQL/MariaDB service
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Set MySQL/MariaDB root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host_all: yes
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
